# Generated by Django 4.2.7 on 2023-12-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_date", models.CharField(max_length=255)),
                ("restaurant_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="restraunt",
            old_name="menu_item",
            new_name="username",
        ),
    ]
